modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "mdoadq"
version = "${version}"
displayName = "Music Disks of a Distinguished Quality"
authors = "satyrnidae (code, music), CaptainZephyrr (music)"
description = '''
Adds some unique music discs to the game.
'''
logoFile = "icon.png"

[[dependencies.mdoadq]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mdoadq]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mdoadq]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"
